---
project: deblur_gan
experiment_desc: fpn

train:
  files_a: &FILES_A /path/to/train/set/of/blurred/images 
  files_b: &FILES_B /path/to/train/set/of/sharp/images 
  size: &SIZE 256
  crop: random
  preload: &PRELOAD false
  preload_size: &PRELOAD_SIZE 0
  #bounds: [0, .9]
  scope: geometric
  corrupt: &CORRUPT
    - name: cutout
      prob: 0.5
      num_holes: 3
      max_h_size: 25
      max_w_size: 25
    - name: jpeg
      quality_lower: 70
      quality_upper: 90
    - name: motion_blur
    - name: median_blur
    - name: gamma
    - name: rgb_shift
    - name: hsv_shift
    - name: sharpen

val:
  files_a: /path/to/test/set/of/blurred/images
  files_b: /path/to/test/set/of/sharp/images
  size: *SIZE
  scope: geometric
  crop: center
  preload: *PRELOAD
  preload_size: *PRELOAD_SIZE
  #bounds: [.9, 1]
  corrupt: *CORRUPT

phase: train
warmup_num: 3
model:
  g_name: fpn_ghostnet_gm_hin #options are fpn_ghostnet, fpn_mobilenet, fpn_mobilenet_v3, fpn_ghostnet_all
  blocks: 9
  d_name: double_gan # no_gan, patch_gan, double_gan, multi_scale
  d_layers: 3
  content_loss: perceptual
  adv_lambda: 0.001
  disc_loss: ragan-ls #wgan-gp
  learn_residual: True
  norm_layer: hin
  dropout: True

num_epochs: 2000
train_batches_per_epoch: 2000
val_batches_per_epoch: 1000
batch_size: 1
image_size: [256, 256]

optimizer:
  name: adam
  lr:   0.0001
scheduler:
  name: linear
  start_epoch: 50
  min_lr: 0.0000001
